version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - TZ=America/Detroit
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
